import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* FAVICON MANGLER */}</head>

      <body className="bg-yellow-50 font-chewy">
        <Sidebar></Sidebar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
